baseURL = "https://pedropalmares.github.io/programmerjourney/"
title = "Programmer Journey"
theme = "ghostwriter"
publishDir = "docs"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Programmer Journey"
    description = "My journey as a programmer"
    opengraph = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"

[menu]