baseURL = "https://pedropalmares.github.io/programmerjourney/"
title = "My blog"
theme = "ghostwriter"
publishDir = "docs"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "My headline"
    description = "My description"
    opengraph = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"