baseURL = "https://www.programmerjourney.com/"
title = "Programmer Journey"
theme = "ghostwriter"
publishDir = "docs"
googleAnalytics = "UA-168158575-1"
disqusShortname = "programmerjourney"

# Enable for syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Programmer Journey"
    description = "My journey as a programmer"
    opengraph = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"